# 量子信号処理 (QSP)

## 理論

### Block encoding

ハミルトニアン $H$ （固有値・固有ベクトル $E_i$, $\ket{E_i}$）のブロックエンコーディングとは、
\begin{align}  
    \alpha H = (\bra{0^m}\otimes I_n) U (\ket{0^m}\otimes I_n)
\end{align}
となる $U$ のこと。

ここで $I_n$ は $H$ のターゲットとなる系に作用する $n$ qubit の恒等演算子。$\alpha$ は $U$ がユニタリになるように調整する係数で、例えば $\|H\|$ にスケールされる。行列成分で表示すると、
\begin{align}
    U = \left(
    \begin{array}{cc}
        \alpha H & \cdot \\
        \cdot & \cdot
    \end{array}
    \right)
\end{align}
という形になる。

$U$ がブロックエンコーディングと呼ばれるには、これさえ満たしていれば他の成分は何でもよいことに注意。例えば $U$ は $\ket{0^m}\ket{E_i}$ に対して、
\begin{align}
    U\ket{0^m}\ket{E_i} = \alpha E_i \ket{0^m}\ket{E_i} + \cdots
\end{align}
のような形で作用する。

この式からもわかるように、$\alpha$ は少なくとも $|\alpha E_i|<1$ が満たされるように決められなければならない。
つまり最低条件として $\alpha < 1/\|H\|$ （$\|H\|$ は $H$ のオペレータノルム）が成り立つ。
補助ビットが $\ket{0^m}$ の空間では $\alpha H$ として作用するため、このようになる。
また、$\cdots$ の部分は $\ket{0^m}\ket{E_i}$ と直交することに注意したい。
これは $\cdots$ の部分が補助ビットが $\ket{0^m}$ でない状態になっているためである。

そこで、
\begin{align}
    U\ket{0^m}\ket{E_i} = \alpha E_i \ket{0^m}\ket{E_i} + \sqrt{1-\alpha^2E_i^2}\ket{g_i}
\end{align}
と書くことにする。
ここで、$\ket{g_i}$ は規格化されたベクトル（$\braket{g_i|g_i}=1$）として定義するために、$\sqrt{1-\alpha^2E_i^2}$ の係数が必要になる。
$\ket{g_i}$ は興味のない空間に行ってしまった成分なので、"garbage" と呼ばれることもある。その頭文字を取って $\ket{g_i}$ と書いた。

### ブロックエンコーディングの具体的な構成方法

ハミルトニアンがパウリの和で書かれていて、
\begin{align}
    H = \sum_i h_i P_i
\end{align}
であるとする。$P_i$ の符号を適切に取ることによって、$h_i$ はすべて正に取れることに注意。$\texttt{PREPARE}$ ゲートを $m$ 量子ビットの補助量子ビット上で 次のような性質を満たすものとして定義する。
\begin{align}
    \texttt{PREPARE}\ket{0^m} = \frac{1}{\sqrt{\sum_i h_i}}\sum_{i} e^{i\phi_i} \sqrt{h_i} \ket{i}
\end{align}
$\phi_i$ は任意の位相で、都合のいいように自由に決めて良い。また $\texttt{SELECT}$ ゲートを次のように定義する。
\begin{align}
    \texttt{SELECT}\ket{i}\ket{\psi} = \ket{i}(P_i\ket{\psi})
\end{align}
\texttt{SELECT} は補助量子ビットレジスタの番号によって指定される (符号を含んだ) パウリ演算子 $P_i$ をターゲット系に作用させるようなゲートである。
これらのゲートによって、
\begin{align}
    U = (\texttt{PREPARE}^\dagger \otimes I_n) \texttt{SELECT} (\texttt{PREPARE}\otimes I_n)
\end{align}
という $U$ を定義するとこれは $H$ のブロックエンコーディングになっている。具体的には
\begin{align}
    H = \frac{1}{\sum_i h_i}(\bra{0^m}\otimes I_n) U (\ket{0^m}\otimes I_n)
\end{align}
である。

このブロックエンコーディングの構成方法では $U^2=I$ が満たされていることに注意したい。今後これを仮定した議論を行う。

### Qubitization

$U$ を $U^2=I$ を満たす $H$ のブロックエンコーディングとする。
$U$ から $H$の固有値固有ベクトルの情報を取り出すために、
中心的な役割を果たすのは $U$ から定義されるユニタリ
\begin{align}
    W &= (2\ket{0^m}\bra{0^m}\otimes I_n -I_{m+n})U 
\end{align}
である。実はこの演算子は、各 $i$ について $\ket{0^m}\ket{E_i}$ と $\ket{g_i}$ で張られる2次元空間内の回転になっている。
グローバーのアルゴリズムや Szegedy によって導入された古典ランダムウォークの量子化 (Szegedy Walk) のような性質を持っているので、ウォーク演算子と呼ぶこともある。このノート内でもそのように呼ぶことにする。回転となっている性質は次のような計算によってわかる。$\ket{0^m}\ket{E_i}$ は $W$ によって次のように変換される。
\begin{align}
    W\ket{0^m}\otimes\ket{E_i} &= 2\left(\ket{0^m}\bra{0^m}\otimes I_n\right) U \ket{0^m}\ket{E_i} - U \ket{0^m}\ket{E_i} \\
    &= 2\alpha E_i \ket{0^m}\ket{E_i} -  \alpha E_i \ket{0^m}\ket{E_i} - \sqrt{1-\alpha^2E_i^2}\ket{g_i} \\
    &= \alpha E_i \ket{0^m}\ket{E_i} - \sqrt{1-\alpha^2E_i^2}\ket{g_i} 
\end{align}
さらに $\ket{g_i}$ は $\sqrt{1-\alpha^2E_i^2}\ket{g_i}=U\ket{0^m}\ket{E_i} - \alpha E_i \ket{0^m}\ket{E_i}$ であることに注意して
\begin{align}
    W\ket{g_i} &= \frac{1}{\sqrt{1-\alpha^2E_i^2}}\left(WU\ket{0^m}\ket{E_i} - \alpha E_i W\ket{0^m}\ket{E_i}\right) \\
    &= \frac{1}{\sqrt{1-\alpha^2E_i^2}}\left(\ket{0^m}\ket{E_i} - \alpha^2 E_i^2 \ket{0^m}\ket{E_i} + \alpha E_i\sqrt{1-\alpha^2E_i^2}\ket{g_i}\right) \\
    &= \sqrt{1-\alpha^2E_i^2}\ket{0^m}\ket{E_i} + \alpha E_i\ket{g_i}
\end{align}
となる。たしかに $W$ は $\ket{0^m}\ket{E_i}$ と $\ket{g_i}$ で張られる空間内で閉じた作用をしていて、$\ket{0^m}\ket{E_i}:=(1~0)^T$ と $\ket{g_i}:=(0~1)^T$ と基底を取った上で行列表示すると
\begin{align}
    \left(\begin{array}{cc}
       \alpha E_i  &  \sqrt{1-\alpha^2E_i^2} \\
       -\sqrt{1-\alpha^2E_i^2}  & \alpha E_i
    \end{array}
    \right)
\end{align}
という行列になっていることがわかった。$H$ の各固有値の情報が 2 次元部分空間 (=qubit) に埋め込まれたという意味で qubitization とも呼ばれる。特に上の行列はこの部分空間での $y$ 軸回転となっている。

### Block encoding と Chebyshev 多項式
Childs らは $W^l$ が次のように書けることを発見した。
\begin{align}
    W^l = \left(\begin{array}{cc}
       T_l(\alpha E_i)  &  \sqrt{1-\alpha^2E_i^2} U_{l-1}(\alpha E_i) \\
       -\sqrt{1-\alpha^2E_i^2}U_{l-1}(\alpha E_i)  & T_l(\alpha E_i)
    \end{array}\right)
\end{align}
ただし $\ket{0^m}\ket{E_i}:=(1~0)^T$ と $\ket{g_i}:=(0~1)^T$ と基底を取った。$T_l, U_l$ はそれぞれ第一種第二種チェビシェフ多項式。

### Block encoding と QSP

ウォーク演算子
\begin{align}
    W &= R_0U = (2\ket{0^m}\bra{0^m}\otimes I_n -I_{m+n})U 
\end{align}
を少し変化させることで、$W$ から $f(H)$ のブロックエンコーディングを構成することができる。具体的には、
\begin{align}
    W_\phi = e^{i\phi (\ket{0^m}\bra{0^m}\otimes I_n)} W e^{-i\phi (\ket{0^m}\bra{0^m}\otimes I_n)}
\end{align}
という演算子 $W_\phi$ を使う。
$e^{-i\phi (\ket{0^m}\bra{0^m}\otimes I_n)}$ の作用を $\ket{0^m}\ket{E_i}:=(1~0)^T$ と $\ket{g_i}:=(0~1)^T$ の基底で行列表示すると、
\begin{align}
    \left(\begin{array}{cc}
       e^{-i\phi}  &  0 \\
       0  & 1
    \end{array}
    \right) \sim \left(\begin{array}{cc}
       e^{-i\phi/2}  &  0 \\
       0  & e^{i\phi/2}
    \end{array}
    \right)
\end{align}
となり、これはこの部分空間内での $R_z(\phi)$ に等しい。一方で $W$ はこの部分空間内で
\begin{align}
    \left(\begin{array}{cc}
       \alpha E_i  &  \sqrt{1-\alpha^2E_i^2} \\
       -\sqrt{1-\alpha^2E_i^2}  & \alpha E_i
    \end{array}
    \right)
\end{align}
となっていたので、これはこの部分空間内での $R_y(\theta_i)$ ($\theta_i = -2\arccos (\alpha E_i)$) に等しい。
つまり $W_\phi$ は部分空間内で、
\begin{align}
    W_\phi = R_z(\phi)R_y(\theta_i)R_z(\phi)^\dagger
\end{align}
と作用する。
実は $W_\phi$ をいろいろな位相 $\phi$ を使って掛け合わせていくことで、$\alpha E_i$ に関して (ほとんど) 任意の関数を得ることができることが、[Low らによって示されている](https://journals.aps.org/prx/abstract/10.1103/PhysRevX.6.041067).


## 実装

大まかな理論は上のような感じだが、特に所望の関数に対応する位相 $\phi$ を得るプロセスは少し煩雑であり、ここで実装するのは簡単ではない。ここでは pennylane にパッケージ化されているものを使ってみる。

In [1]:
# simple circuit on pennylane
import pennylane as qml

dev = qml.device("default.qubit", wires=1)
@qml.qnode(dev)
def circuit():
    qml.X(wires=0)
    qml.Y(wires=0)
    return qml.expval(qml.PauliZ(0))
qml.draw(circuit)()

'0: ──X──Y─┤  <Z>'

## Block encoding の実装

In [27]:
dev = qml.device("default.qubit", wires=3)
H = qml.dot([0.2, 0.8,], [qml.X(0), qml.Z(0)@qml.Z(1)])
print(qml.matrix(H))
@qml.qnode(dev)
def circuit():
    qml.PrepSelPrep(H.map_wires({0: 1, 1: 2}), control=[0,])
    return qml.probs(wires=[0, 1, 2])
print(qml.draw(circuit)())
compiled = qml.compile(circuit)
print("compiled circuit")
print(qml.draw(compiled)())
print("matrix representation")
matrix = qml.matrix(compiled)()
print(matrix.real)

[[ 0.8+0.j  0. +0.j  0.2+0.j  0. +0.j]
 [ 0. +0.j -0.8+0.j  0. +0.j  0.2+0.j]
 [ 0.2+0.j  0. +0.j -0.8+0.j  0. +0.j]
 [ 0. +0.j  0.2+0.j  0. +0.j  0.8+0.j]]
0: ─╭PrepSelPrep(0.20,0.80)─┤ ╭Probs
1: ─├PrepSelPrep(0.20,0.80)─┤ ├Probs
2: ─╰PrepSelPrep(0.20,0.80)─┤ ╰Probs
compiled circuit
0: ──RY(2.21)──X─╭●──X─╭●─╭●──RY(-2.21)─┤ ╭Probs
1: ──────────────╰X────│──╰Z────────────┤ ├Probs
2: ────────────────────╰Z───────────────┤ ╰Probs
matrix representation
[[ 0.8  0.   0.2  0.   0.4  0.  -0.4  0. ]
 [ 0.  -0.8  0.   0.2  0.  -0.4  0.  -0.4]
 [ 0.2  0.  -0.8  0.  -0.4  0.  -0.4  0. ]
 [ 0.   0.2  0.   0.8  0.  -0.4  0.   0.4]
 [ 0.4  0.  -0.4  0.   0.2  0.   0.8  0. ]
 [ 0.  -0.4  0.  -0.4  0.  -0.2  0.   0.8]
 [-0.4  0.  -0.4  0.   0.8  0.  -0.2  0. ]
 [ 0.  -0.4  0.   0.4  0.   0.8  0.   0.2]]


たしかに block-encoding になっていることがわかる

# QSP (QSVT) の実装

In [35]:
dev = qml.device("default.qubit", wires=3)
H = qml.dot([0.2, 0.8,], [qml.X(0), qml.Z(0)@qml.Z(1)])
print((qml.matrix(H)).real/2 + (qml.matrix(H) @ qml.matrix(H) @ qml.matrix(H)).real/2)
@qml.qnode(dev)
def circuit():
    target_poly = [0, .5, 0, .5] # target_poly[i] is the coef to x**i
    qml.qsvt(H.map_wires({0:1,1:2}), target_poly, encoding_wires=[0,], block_encoding="qubitization")
    return qml.probs(wires=[0, 1, 2])
compiled = qml.compile(circuit)
print("compiled circuit")
print(qml.draw(compiled)())
print("matrix representation")
matrix = qml.matrix(compiled)()
print(np.round(matrix.real, 4))

[[ 0.672  0.     0.168  0.   ]
 [ 0.    -0.672  0.     0.168]
 [ 0.168  0.    -0.672  0.   ]
 [ 0.     0.168  0.     0.672]]
compiled circuit
0: ─╭∏_ϕ(-2.36)──GlobalPhase(3.14)──I──X──Rϕ(3.14)──X──I──RY(2.21)──X─╭●──X─╭●─╭●──RY(-2.21)
1: ─├∏_ϕ(-2.36)──GlobalPhase(3.14)────────────────────────────────────╰X────│──╰Z───────────
2: ─╰∏_ϕ(-2.36)──GlobalPhase(3.14)──────────────────────────────────────────╰Z──────────────

──╭∏_ϕ(1.57)──RY(2.21)─╭●─╭●──X─╭●──X──RY(-2.21)──I──X──Rϕ(-3.14)──X──I──GlobalPhase(-3.14)
──├∏_ϕ(1.57)───────────╰Z─│─────╰X───────────────────────────────────────GlobalPhase(-3.14)
──╰∏_ϕ(1.57)──────────────╰Z─────────────────────────────────────────────GlobalPhase(-3.14)

──╭∏_ϕ(0.36)──GlobalPhase(3.14)──I──X──Rϕ(3.14)──X──I──RY(2.21)──X─╭●──X─╭●─╭●──RY(-2.21)─╭∏_ϕ(0.42)─┤
──├∏_ϕ(0.36)──GlobalPhase(3.14)────────────────────────────────────╰X────│──╰Z────────────├∏_ϕ(0.42)─┤
──╰∏_ϕ(0.36)──GlobalPhase(3.14)──────────────────────────────────────────╰Z───────────────╰∏_ϕ(